dependencies {

    //modCompileOnly("curse.maven:gt-985872:6816503") //gtnn
    modCompileOnly("curse.maven:gt-985872:6851587") //gtnn 1.3.2
//    modCompileOnly("curse.maven:gt-985872:6764684") //gtnn 1.3.0

    compileOnly(libs.jetbrains.annotations)

    jarJar(modApi(forge.gtceu.get()))

    // LDLib
    jarJar(modApi(forge.ldlib.get()))

    // Registrate
    jarJar(modApi(forge.registrate.get()))

    // Configuration
    jarJar(modApi(forge.configuration.get()))

    // Mixin (& Extras)
    annotationProcessor(variantOf(libs.mixin) { classifier("processor") })
    annotationProcessor(forge.mixinExtras.common)
    api(forge.mixinExtras.common)
    jarJar(forge.mixinExtras.forge)

    testImplementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
}
