org.gradle.jvmargs = -Xmx6G
org.gradle.java.installations.auto-download=false
org.gradle.parallel = true
org.gradle.caching = true

# Mod Info
mod_id = gtca
mod_name = GT Community Additions
mod_version = 2.3.0
mod_description = GT Modern Addon 
mod_license = LGPL-3.0 license
mod_url = https://github.com/mordgren/gtca/
mod_issue_tracker = https://github.com/mordgren/gtca/issues/
maven_group = net.mordgren.gtca