modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"

# This is a URL to e.g. your GitHub or CurseForge issues page.
# It will appear in any crash reports this mod is directly involved in.
# issueTrackerURL="https://github.com/invalid/pleasechangeme/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]]
    modId = "gtca"
    version = "1.0.1a"
    displayName = "${mod_name}"
    displayURL = "${mod_url}"
    # This will be displayed as your mod's logo in the Mods panel.
    # logoFile="icon.png" #optional
    # Some more fluff displayed in the Mods panel. Feel free to issue your special thanks here!
    # credits="Thanks to Mojang for making this great game" #optional
    # Some more fluff displayed in the Mods panel. Plug your stuff here!
    authors="${mod_author}"
    description = '''
Example Description
...ain is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain,... (Lorem Ipsum translated to english.)
'''

    [[dependencies.gtca]]
        modId = "forge"
        mandatory = true
        versionRange = "[47.3.7,)"
        ordering = "NONE"
        side = "BOTH"
    [[dependencies.gtca]]
        modId = "minecraft"
        mandatory = true
        versionRange = "[1.20.1,)"
        ordering = "NONE"
        side = "BOTH"
    [[dependencies.gtca]]
        modId = "gtceu"
        mandatory = true
        versionRange = "[1.4.1+patch.2,)"
        ordering = "AFTER"
        side = "BOTH"
